//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

/// <summary>
/// Interface class for Player controlled by virtual joystick
/// </summary>
public class IPlayer : MonoBehaviour
{
	/// <summary>
	/// Raises the stick changed event when 
	/// the position of the virtual joystick has changed
	/// </summary>
	/// <param name="distance">of the change</param>
	/// <param name="stickPos">Stick position (coordinates)</param>
	public virtual void OnStickChanged(float distance, Vector2 stickPos)
	{
	}
}


